language: go
sudo: false

services:
  - docker

before_install:
  - echo "hello install"
install:
  - echo "install"

jobs:
  include:
    - stage: build
      script: docker build --no-cache -t ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} .
    - stage: test
      # docker run ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} /go/src/github.com/kainlite/whatismyip-go/whatismyip-go.test
      script: echo "docker test" 
    - stage: push_docker_image
      # docker run ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} /go/src/github.com/kainlite/whatismyip-go/whatismyip-go.test
      script: 
        - export DOCKER_USER=haodiaodemingzi
        - export DOCKER_PASS=king1984td21
        - export IMAGE=haodiaodemingzi/pipelines-go:${TRAVIS_COMMIT}
        - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
        - docker push $IMAGE
    - stage: deploy
      deploy: &rancher
        provider: rancher
        app: deploy-demo
        script: echo "test deploy"
        on:
          branch: master
